# App Engine configuration for SparzaFI
runtime: python311

instance_class: F2

env_variables:
  FLASK_ENV: "production"
  FLASK_DEBUG: "False"
  FIREBASE_SERVICE_ACCOUNT: "firebase-service-account.json"

entrypoint: gunicorn -b :$PORT app:app

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 80

handlers:
- url: /static
  static_dir: static
  secure: always

- url: /.*
  script: auto
  secure: always
